[features]
seeds = false

[test.validator]
url = "https://api.devnet.solana.com"

# pyth_account
[[test.validator.clone]]
address = "J83w4HKfqxwcq3BEMMkPFSppX3gqekLyLJBexebFVkix"
[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
[[test.validator.clone]]
address = "PwDiXFxQsGra4sFFTT8r1QWRMd4vfumiWC1jfWNfdYT"

[programs.localnet]
betting = "CkjLXWUbYttpTxDXvSxy3gwzA7PUfxs2W25F7kR7zE2j"

[programs.devnet]
betting = "CkjLXWUbYttpTxDXvSxy3gwzA7PUfxs2W25F7kR7zE2j"

[programs.mainnet]
betting = "CkjLXWUbYttpTxDXvSxy3gwzA7PUfxs2W25F7kR7zE2j"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "./test-key.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
